package com.springrest.employeecms.model;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import com.springrest.employeecms.enums.LoanTypeEnum;

@Entity
public class Loan {

	@Id
    @GeneratedValue(strategy = GenerationType.AUTO) // Auto generated by Hibernate
    private Long id;
	
	private String loanNumber;
	
	@Enumerated(EnumType.STRING)
	private LoanTypeEnum type;
	
	private Double interestRate;
	public Double getInterestRate() {
		return interestRate;
	}
	public void setInterestRate(Double interestRate) {
		this.interestRate = interestRate;
	}
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getLoanNumber() {
		return loanNumber;
	}
	public void setLoanNumber(String loanNumber) {
		this.loanNumber = loanNumber;
	}
	public LoanTypeEnum getType() {
		return type;
	}
	public void setType(LoanTypeEnum type) {
		this.type = type;
	}
	
	
}
